In [161]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [162]:
dataset = pd.read_csv('Data3.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [163]:
print(x)

[['Indonesia' 40.0 70000.0]
 ['Malaysia' 25.0 47000.0]
 ['Thailand' nan 54000.0]
 ['Vietnam' 31.0 63000.0]
 ['Kamboja' 27.0 59000.0]
 ['Indonesia' 35.0 59000.0]
 ['Vietnam' 43.0 51000.0]
 ['Malaysia' 39.0 nan]
 ['Filipina' 48.0 73000.0]
 ['Thailand' 37.0 69000.0]]


In [164]:
print(y)

['Tidak' 'Tidak' 'Ya' 'Ya' 'Ya' 'Tidak' 'Ya' 'Tidak' 'Ya' 'Tidak']


In [165]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [166]:
print(x)

[['Indonesia' 40.0 70000.0]
 ['Malaysia' 25.0 47000.0]
 ['Thailand' 36.111111111111114 54000.0]
 ['Vietnam' 31.0 63000.0]
 ['Kamboja' 27.0 59000.0]
 ['Indonesia' 35.0 59000.0]
 ['Vietnam' 43.0 51000.0]
 ['Malaysia' 39.0 60555.555555555555]
 ['Filipina' 48.0 73000.0]
 ['Thailand' 37.0 69000.0]]


In [167]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [168]:
print(x)

[[0.0 1.0 0.0 0.0 0.0 0.0 40.0 70000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 25.0 47000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 36.111111111111114 54000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 31.0 63000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 27.0 59000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 35.0 59000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 43.0 51000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 39.0 60555.555555555555]
 [1.0 0.0 0.0 0.0 0.0 0.0 48.0 73000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 37.0 69000.0]]


In [169]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [170]:
print(y)

[0 0 1 1 1 0 1 0 1 0]


In [171]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [172]:
print(x_train)   

[[0.0 0.0 0.0 0.0 0.0 1.0 43.0 51000.0]
 [0.0 0.0 1.0 0.0 0.0 0.0 27.0 59000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 40.0 70000.0]
 [0.0 0.0 0.0 0.0 0.0 1.0 31.0 63000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 25.0 47000.0]
 [0.0 0.0 0.0 1.0 0.0 0.0 39.0 60555.555555555555]
 [1.0 0.0 0.0 0.0 0.0 0.0 48.0 73000.0]
 [0.0 1.0 0.0 0.0 0.0 0.0 35.0 59000.0]]


In [173]:
print(x_test)

[[0.0 0.0 0.0 0.0 1.0 0.0 36.111111111111114 54000.0]
 [0.0 0.0 0.0 0.0 1.0 0.0 37.0 69000.0]]


In [174]:
print(y_train)

[1 1 0 1 0 0 1 0]


In [175]:
print(y_test)

[1 0]


In [176]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [177]:
print(x_train)

[[0.0 0.0 0.0 -0.5773502691896258 0.0 1.7320508075688774
  0.9375093422553951 -1.1455266556164283]
 [0.0 0.0 1.0 -0.5773502691896258 0.0 -0.5773502691896258
  -1.2053691543283651 -0.16218335660739305]
 [0.0 1.0 0.0 -0.5773502691896258 0.0 -0.5773502691896258
  0.5357196241459401 1.1899136795300302]
 [0.0 0.0 0.0 -0.5773502691896258 0.0 1.7320508075688774
  -0.669649530182425 0.32948829289712456]
 [0.0 0.0 0.0 1.7320508075688774 0.0 -0.5773502691896258
  -1.4732289664013352 -1.6371983051209458]
 [0.0 0.0 0.0 1.7320508075688774 0.0 -0.5773502691896258
  0.401789718109455 0.02902228486658591]
 [1.0 0.0 0.0 -0.5773502691896258 0.0 -0.5773502691896258
  1.60715887243782 1.5586674166584185]
 [0.0 1.0 0.0 -0.5773502691896258 0.0 -0.5773502691896258
  -0.13392990603648502 -0.16218335660739305]]


In [178]:
print(x_test)

[[0.0 0.0 0.0 -0.5773502691896258 1.0 -0.5773502691896258
  0.01488110067072098 -0.7767729184880401]
 [0.0 0.0 0.0 -0.5773502691896258 1.0 -0.5773502691896258
  0.13392990603648502 1.066995767153901]]
